mongoDb: movie-ratings
mongoURI: mongodb://localhost:32768/movie-ratings?w=1
jwtSigningKey: 23214F888132773A753654BC8D4E7FBB2670954D8C599568FB77F86C49CA6F5C
jwtTokenTTLInHours: 336
redisURI: redis://localhost:32769
computedRatingsCacheTTLInSeconds: 3600
externalRatingsCacheTTLInSeconds: 86400
userCacheTTLInSeconds: 28800
